<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net$(DotNetVersion)-ios</TargetFramework>
        <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
        <Nullable>disable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <CodesignKey>Apple Development: thomas kefauver (MY7R67BXWM)</CodesignKey>
        <CodesignProvision>tk ios dev</CodesignProvision>
        <ArchiveOnBuild>true</ArchiveOnBuild>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(IsPublishMode)' == 'true'">
        <CodesignKey>Apple Distribution: thomas kefauver (3382GDS46D)</CodesignKey>
        <CodesignProvision>cc ios dist</CodesignProvision>
    </PropertyGroup>
        
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
       <PublishAot>false</PublishAot>
    </PropertyGroup>
        
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
      <PublishAot>false</PublishAot>
      <MtouchLink>SdkOnly</MtouchLink>
      <MtouchDebug>true</MtouchDebug>
      <IOSDebugOverWiFi>true</IOSDebugOverWiFi>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Avalonia.iOS" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Calcuchord\Calcuchord.csproj"/>
    </ItemGroup>
    
    <ItemGroup>
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-60x60%402x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-60x60%402x.png</Link>
      </ImageAsset>
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-76x76%401x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-76x76%401x.png</Link>
      </ImageAsset>
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-40x40%403x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-40x40%403x.png</Link>
      </ImageAsset>
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-29x29%402x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-29x29%402x.png</Link>
      </ImageAsset>
        
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-29x29%403x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-29x29%403x.png</Link>
      </ImageAsset>
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-40x40%402x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-40x40%402x.png</Link>
      </ImageAsset>
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-60x60%403x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-60x60%403x.png</Link>
      </ImageAsset>
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-20x20%402x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-20x20%402x.png</Link>
      </ImageAsset>
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-20x20%403x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-20x20%403x.png</Link>
      </ImageAsset>
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-83.5x83.5%402x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-83.5x83.5%402x.png</Link>
      </ImageAsset>
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-1024x1024%401x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-1024x1024%401x.png</Link>
      </ImageAsset>
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-20x20%401x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-20x20%401x.png</Link>
      </ImageAsset>
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-40x40%401x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-40x40%401x.png</Link>
      </ImageAsset>
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-76x76%402x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-76x76%402x.png</Link>
      </ImageAsset>
      <ImageAsset Update="Media.xcassets\AppIcon.appiconset\app_icon-29x29%401x.png">
        <Link>Media.xcassets\AppIcon.appiconset\app_icon-29x29%401x.png</Link>
      </ImageAsset>
    </ItemGroup>
</Project>
