<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net$(DotNetVersion)</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <NoWarn>$(NoWarn);CS7035;</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <Version>1.0.0</Version>
        <AssemblyVersion>1.0.*</AssemblyVersion>
        <Deterministic>false</Deterministic>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.ReactiveUI"/>
        <PackageReference Include="Avalonia.Svg.Skia"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <PackageReference Include="iTextSharp" />
        <PackageReference Include="Material.Avalonia"/>
        <PackageReference Include="Material.Avalonia.Dialogs"/>
        <PackageReference Include="Material.Icons.Avalonia"/>
        <PackageReference Include="Melanchall.DryWetMidi.Nativeless"/>
        <PackageReference Include="MonkeyPaste.Common.Avalonia"/>
        <PackageReference Include="org.matheval"/>

        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="DialogHost.Avalonia"/>
        <PackageReference Include="fody">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="PropertyChanged.Fody" PrivateAssets="All"/>
        <PackageReference Include="ReactiveUI"/>
        <PackageReference Include="System.Formats.Nrbf"/>
        <PackageReference Include="Material.Avalonia.DataGrid"/>
        <PackageReference Include="Avalonia.Controls.DataGrid"/>
    </ItemGroup>


    <ItemGroup>
        <ReferencePathWithRefAssemblies Update="\home\tkefauver\.nuget\packages\newtonsoft.json\13.0.3\lib\net6.0\Newtonsoft.Json.dll"/>
    </ItemGroup>


    <ItemGroup>
        <Compile Update="Views\Popups\Overlays\BusyOverlayView.axaml.cs">
            <DependentUpon>BusyOverlayView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Popups\Dialogs\ProgressView.axaml.cs">
            <DependentUpon>ProgressView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Popups\Dialogs\TextFieldDialogView.axaml.cs">
            <DependentUpon>TextFieldDialogView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
    </ItemGroup>
</Project>
